---
title: "Untitled"
author: "Gabrielle Bartomeo"
date: "February 11, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
directory <- "D:/CUNY SPS Data Science Masters/DATA 621/Assignment 01/data/"
library(ggplot2)
library(ggcorrplot)
library(Matrix)
library(gridExtra)
set.seed(123)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
moneyball_eval <- read.csv(paste(directory, "moneyball-evaluation-data.csv", sep=""))
moneyball_train <- read.csv(paste(directory, "moneyball-training-data.csv", sep=""))[,-1] # use me
```

# Training Exploration

## Summary()

```{r}
summary(moneyball_train)
```

## Standard Deviation

```{r}
sapply(moneyball_train[complete.cases(moneyball_train),], sd)
```

## Boxplots

```{r fig.height=6, fig.width=6}
ggplot(stack(moneyball_train[complete.cases(moneyball_train),]), aes(x=ind, y=values)) + 
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

## Point plots

```{r}
ggplot(data=moneyball_train[complete.cases(moneyball_train),], aes(x=TARGET_WINS)) +
  geom_point(aes(y=TEAM_BATTING_H, color="Base Hits by Batters"), alpha=0.1) +
  geom_point(aes(y=TEAM_BATTING_2B, color="Doubles by Batters"), alpha=0.1) +
  geom_point(aes(y=TEAM_BATTING_3B, color="Triples by Batters"), alpha=0.1) +
  geom_point(aes(y=TEAM_BATTING_HR, color="Homeruns by Batters"), alpha=0.1) +
  geom_point(aes(y=TEAM_BATTING_BB, color="Walks by Batters"), alpha=0.1) +
  geom_point(aes(y=TEAM_BATTING_SO, color="Strikeouts by Batters"), alpha=0.1) +
  geom_point(aes(y=TEAM_BASERUN_SB, color="Stolen Bases"), alpha=0.1) +
  geom_point(aes(y=TEAM_BASERUN_CS, color="Caught Stealing"), alpha=0.1) +
  geom_point(aes(y=TEAM_BATTING_HBP, color="Batters Hit by Pitch"), alpha=0.1) +
  geom_point(aes(y=TEAM_PITCHING_H, color="Hits Allowed"), alpha=0.1) +
  geom_point(aes(y=TEAM_PITCHING_HR, color="Homeruns Allowed"), alpha=0.1) +
  geom_point(aes(y=TEAM_PITCHING_SO, color="Strikeouts by Pitchers"), alpha=0.1) +
  geom_point(aes(y=TEAM_FIELDING_E, color="Errors"), alpha=0.05) +
  geom_point(aes(y=TEAM_FIELDING_DP, color="Double Plays"), alpha=0.1) +
  labs(color="Variables", ylab="Variables")
```

## Correlation

```{r fig.height=6, fig.width=6}
ggcorrplot(as.data.frame(round(cor(moneyball_train[complete.cases(moneyball_train),]), 3)), 
           type="upper", lab=TRUE, lab_size=2)
```


## Missing values by variable

```{r}
sapply(moneyball_train, function(x) sum(is.na(x)))
```

